/**
 * Command Code capability snapshot.
 *
 * AUTO-GENERATED by _extract-capabilities.mjs from the installed
 * @mars-sea/dsh-commandcode-provider bundle (which tracks
 * command-code@1.53.0). The Command Code Provider API exposes no plan,
 * reasoning-effort, or modality metadata, so these tables are the source
 * of truth for the model picker's annotations and for image gating.
 *
 * Re-run the generator after a Command Code release reshuffles models,
 * plans, or prices.
 */

/** Minimum subscription tier a catalog model belongs to. */
export type PlanTier = "go" | "goat" | "pro" | "provider" | "max";

/** One subscription plan: display name, monthly credit grant, tier rank. */
export interface SubscriptionPlan {
	name: string;
	monthlyCredits: number;
	tierWeight: number;
}
export const KNOWN_EFFORTS: Record<string, string[]> = {
  "Qwen/Qwen3.8-Max": [
    "low",
    "medium",
    "xhigh"
  ],
  "Qwen/Qwen3.8-Max-0902": [
    "low",
    "medium",
    "xhigh"
  ],
  "Qwen/Qwen3.8-27B": [
    "low",
    "medium",
    "xhigh"
  ],
  "Qwen/Qwen3.8-Flash": [
    "low",
    "medium",
    "xhigh"
  ],
  "claude-fable-5-1": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "claude-fable-5": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "claude-opus-4-7": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "claude-opus-4-8": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "claude-opus-5": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "claude-sonnet-4-6": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "claude-sonnet-5": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "deepseek/deepseek-v4-flash-fast": [
    "low",
    "high",
    "max"
  ],
  "deepseek/deepseek-v4.1-flash": [
    "low",
    "high",
    "max"
  ],
  "deepseek/deepseek-v4-flash": [
    "high",
    "max"
  ],
  "deepseek/deepseek-v4-flash-vision-exp": [
    "high",
    "max"
  ],
  "deepseek/deepseek-v4-pro": [
    "high",
    "max"
  ],
  "google/gemini-3.1-flash-lite": [
    "low",
    "medium",
    "high"
  ],
  "google/gemini-3.5-flash": [
    "low",
    "medium",
    "high"
  ],
  "google/gemini-3.5-flash-lite": [
    "low",
    "medium",
    "high"
  ],
  "google/gemini-3.6-flash": [
    "low",
    "medium",
    "high"
  ],
  "google/gemini-3.7-flash": [
    "low",
    "medium",
    "high"
  ],
  "gpt-5.3-codex": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "gpt-5.4": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "gpt-5.4-mini": [
    "low",
    "medium",
    "high"
  ],
  "gpt-5.5": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "gpt-5.6-luna": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "gpt-5.6-sol": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "gpt-5.6-terra": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "moonshotai/Kimi-K3": [
    "low",
    "high",
    "max"
  ],
  "google/gemini-3.8-flash": [
    "low",
    "medium",
    "high"
  ],
  "sakana/fugu-ultra": [
    "high",
    "xhigh"
  ],
  "tencent/hy4-preview": [
    "low",
    "medium",
    "high"
  ],
  "xai/grok-4.5": [
    "low",
    "medium",
    "high"
  ],
  "xai/grok-4.6": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "z-ai/glm-5.3-flash": [
    "low",
    "high",
    "max"
  ],
  "zai-org/GLM-5.2": [
    "high",
    "max"
  ],
  "zai-org/GLM-5.3": [
    "low",
    "high",
    "max"
  ],
  "meta/muse-spark-1.1": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "meta/muse-spark-1.2": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "meta/muse-spark-1.2-contributor": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "meta/muse-spark-1.3": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "meta/muse-spark-1.3-contributor": [
    "low",
    "medium",
    "high",
    "xhigh"
  ],
  "gpt-6-astra": [
    "low",
    "medium",
    "high",
    "xhigh",
    "max"
  ],
  "MiniMaxAI/MiniMax-M3": [
    "low",
    "medium",
    "high"
  ]
};

export const KNOWN_IMAGE_MODELS: string[] = [
  "MiniMaxAI/MiniMax-M3",
  "Qwen/Qwen3.6-Plus",
  "Qwen/Qwen3.7-Flash",
  "Qwen/Qwen3.7-Plus",
  "Qwen/Qwen3.8-27B",
  "Qwen/Qwen3.8-Flash",
  "Qwen/Qwen3.8-Max",
  "Qwen/Qwen3.8-Max-0902",
  "claude-fable-5-1",
  "claude-fable-5",
  "claude-haiku-4-5-20251001",
  "claude-opus-4-7",
  "claude-opus-4-8",
  "claude-opus-5",
  "claude-sonnet-4-6",
  "claude-sonnet-5",
  "deepseek/deepseek-v4-flash-vision-exp",
  "deepseek/deepseek-v4.1-flash",
  "google/gemini-3.1-flash-lite",
  "google/gemini-3.5-flash",
  "google/gemini-3.5-flash-lite",
  "google/gemini-3.6-flash",
  "google/gemini-3.7-flash",
  "google/gemini-3.8-flash",
  "gpt-5.3-codex",
  "gpt-5.4",
  "gpt-5.4-mini",
  "gpt-5.5",
  "gpt-5.6-luna",
  "gpt-5.6-sol",
  "gpt-5.6-terra",
  "gpt-6-astra",
  "meta/muse-spark-1.1",
  "meta/muse-spark-1.2",
  "meta/muse-spark-1.2-contributor",
  "meta/muse-spark-1.3",
  "meta/muse-spark-1.3-contributor",
  "moonshotai/Kimi-K2.5",
  "moonshotai/Kimi-K2.6",
  "moonshotai/Kimi-K2.7-Code",
  "moonshotai/Kimi-K2.7-Code-Highspeed",
  "moonshotai/Kimi-K3",
  "sakana/fugu-ultra",
  "stepfun/Step-3.7-Flash",
  "thinkingmachines/inkling",
  "thinkingmachines/inkling-small",
  "xai/grok-4.5",
  "xai/grok-4.6",
  "xiaomi/mimo-v2.5",
  "z-ai/glm-5.3-flash"
];

export const KNOWN_THINKING_MODELS: string[] = [
  "Qwen/Qwen3.6-Max-Preview",
  "Qwen/Qwen3.6-Plus",
  "Qwen/Qwen3.7-Flash",
  "Qwen/Qwen3.7-Max",
  "Qwen/Qwen3.7-Plus",
  "moonshotai/Kimi-K2.7-Code",
  "moonshotai/Kimi-K2.7-Code-Highspeed",
  "stepfun/Step-3.5-Flash",
  "stepfun/Step-3.7-Flash",
  "tencent/hy3-paid",
  "nvidia/nemotron-3-ultra-550b-a55b",
  "thinkingmachines/inkling",
  "thinkingmachines/inkling-small",
  "poolside/laguna-s-2.1-free",
  "meituan/LongCat-2.0:free",
  "inclusionai/ling-3.0-flash-sante:free"
];

export const KNOWN_PLANS: Record<string, PlanTier> = {
  "MiniMaxAI/MiniMax-M2.5": "go",
  "MiniMaxAI/MiniMax-M2.7": "go",
  "MiniMaxAI/MiniMax-M3": "go",
  "Qwen/Qwen3.6-Max-Preview": "go",
  "Qwen/Qwen3.6-Plus": "go",
  "Qwen/Qwen3.7-Flash": "go",
  "Qwen/Qwen3.7-Max": "go",
  "Qwen/Qwen3.7-Plus": "go",
  "Qwen/Qwen3.8-27B": "go",
  "Qwen/Qwen3.8-Flash": "go",
  "Qwen/Qwen3.8-Max": "go",
  "Qwen/Qwen3.8-Max-0902": "go",
  "deepseek/deepseek-v4-flash-fast": "go",
  "deepseek/deepseek-v4.1-flash": "go",
  "deepseek/deepseek-v4-flash": "go",
  "deepseek/deepseek-v4-flash-vision-exp": "go",
  "deepseek/deepseek-v4-pro": "go",
  "gpt-5.6-luna": "go",
  "meituan/LongCat-2.0:free": "go",
  "inclusionai/ling-3.0-flash-sante:free": "go",
  "meta/muse-spark-1.2-contributor": "go",
  "meta/muse-spark-1.3-contributor": "go",
  "moonshotai/Kimi-K2.5": "go",
  "moonshotai/Kimi-K2.6": "go",
  "moonshotai/Kimi-K2.7-Code": "go",
  "moonshotai/Kimi-K2.7-Code-Highspeed": "go",
  "moonshotai/Kimi-K3": "go",
  "nvidia/nemotron-3-ultra-550b-a55b": "go",
  "poolside/laguna-s-2.1-free": "go",
  "stepfun/Step-3.5-Flash": "go",
  "stepfun/Step-3.7-Flash": "go",
  "tencent/hy3-paid": "go",
  "tencent/hy4-preview": "go",
  "thinkingmachines/inkling": "go",
  "thinkingmachines/inkling-small": "go",
  "xai/grok-4.5": "go",
  "xiaomi/mimo-v2.5": "go",
  "xiaomi/mimo-v2.5-pro": "go",
  "z-ai/glm-5.3-flash": "go",
  "zai-org/GLM-5": "go",
  "zai-org/GLM-5.1": "go",
  "zai-org/GLM-5.2": "go",
  "zai-org/GLM-5.2-Fast": "go",
  "zai-org/GLM-5.3": "go",
  "google/gemini-3.7-flash": "goat",
  "google/gemini-3.8-flash": "goat",
  "gpt-5.6-sol": "goat",
  "meta/muse-spark-1.2": "goat",
  "meta/muse-spark-1.3": "goat",
  "xai/grok-4.6": "goat",
  "claude-haiku-4-5-20251001": "pro",
  "claude-sonnet-4-6": "pro",
  "claude-sonnet-5": "pro",
  "google/gemini-3.1-flash-lite": "pro",
  "google/gemini-3.5-flash": "pro",
  "google/gemini-3.5-flash-lite": "pro",
  "google/gemini-3.6-flash": "pro",
  "gpt-5.3-codex": "pro",
  "gpt-5.4": "pro",
  "gpt-5.4-mini": "pro",
  "gpt-5.5": "pro",
  "gpt-5.6-terra": "pro",
  "meta/muse-spark-1.1": "pro",
  "claude-fable-5-1": "provider",
  "claude-fable-5": "provider",
  "claude-opus-4-7": "provider",
  "claude-opus-4-8": "provider",
  "claude-opus-5": "provider",
  "gpt-6-astra": "provider",
  "sakana/fugu-ultra": "provider"
};

export const PLAN_LABELS: Record<PlanTier, string> = {
  "go": "Go",
  "goat": "GOAT",
  "pro": "Pro",
  "provider": "Provider",
  "max": "Max"
};

export const PLAN_ORDER: Record<PlanTier, number> = {
  "go": 0,
  "goat": 1,
  "pro": 2,
  "provider": 3,
  "max": 4
};

export const KNOWN_DEALS: Record<string, { label: string; free?: boolean }> = {
  "MiniMaxAI/MiniMax-M3": {
    "label": "50% off"
  },
  "xiaomi/mimo-v2.5-pro": {
    "label": "99% off"
  },
  "xiaomi/mimo-v2.5": {
    "label": "98% off"
  },
  "poolside/laguna-s-2.1-free": {
    "label": "FREE",
    "free": true
  },
  "meituan/LongCat-2.0:free": {
    "label": "FREE",
    "free": true
  },
  "inclusionai/ling-3.0-flash-sante:free": {
    "label": "FREE",
    "free": true
  }
};

export const KNOWN_PEAK_PRICING: string[] = [
  "deepseek/deepseek-v4-pro",
  "deepseek/deepseek-v4-flash",
  "deepseek/deepseek-v4-flash-vision-exp",
  "deepseek/deepseek-v4.1-flash"
];

export const KNOWN_SUBSCRIPTION_PLANS: Record<string, SubscriptionPlan> = {
  "individual-go": {
    "name": "Go",
    "monthlyCredits": 10,
    "tierWeight": 0
  },
  "individual-goat": {
    "name": "GOAT",
    "monthlyCredits": 70,
    "tierWeight": 1
  },
  "individual-pro": {
    "name": "Pro",
    "monthlyCredits": 30,
    "tierWeight": 2
  },
  "individual-pro-v1": {
    "name": "Pro",
    "monthlyCredits": 80,
    "tierWeight": 2
  },
  "individual-provider": {
    "name": "Provider",
    "monthlyCredits": 15,
    "tierWeight": 3
  },
  "individual-max": {
    "name": "Max",
    "monthlyCredits": 150,
    "tierWeight": 4
  },
  "individual-ultra": {
    "name": "Ultra",
    "monthlyCredits": 300,
    "tierWeight": 4
  },
  "teams-pro": {
    "name": "Teams Pro",
    "monthlyCredits": 40,
    "tierWeight": 2
  }
};

/** Membership sets for the two modality/effort snapshots above. */
export const KNOWN_IMAGE_MODEL_SET = new Set(KNOWN_IMAGE_MODELS);
export const KNOWN_PEAK_PRICING_SET = new Set(KNOWN_PEAK_PRICING);

/** Plan-id prefixes, longest first — the CLI's own prefix-match order. */
const SUBSCRIPTION_PLAN_PREFIXES = Object.keys(KNOWN_SUBSCRIPTION_PLANS).sort((a, b) => b.length - a.length);

/**
 * Resolve a subscription `planId` (e.g. `individual-pro-v1`) to its display
 * name and monthly credit grant, mirroring the CLI's `getPlanInfo`:
 * normalize (lowercase, `_` → `-`), then longest-prefix match so
 * `individual-pro-v1` wins over `individual-pro`. Unknown ids return
 * `undefined`.
 */
export function subscriptionPlanInfo(planId: string): SubscriptionPlan | undefined {
	const normalized = planId.toLowerCase().replace(/_/g, "-");
	const prefix = SUBSCRIPTION_PLAN_PREFIXES.find((candidate) => normalized.startsWith(candidate));
	return prefix === undefined ? undefined : KNOWN_SUBSCRIPTION_PLANS[prefix];
}
